# Cryptographic identities for peers, orderers, validators
OrdererOrgs:
  - Name: OrdererOrg
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: ValidatorOrg
    Domain: validator.example.com
    EnableNodeOUs: true
    Template:
      Count: 5
    Users:
      Count: 1
